spring:
  application:
    name: sem6
  datasource:
    url: jdbc:mysql://localhost:3306/sem6
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

server:
  port: 8090